/**
 * 命令分类（源自 README「Linux 命令分类」）。
 * 名称会与实际 command/*.md 交叉校验，不存在的条目会被忽略。
 */
export const CATEGORIES = [
    {
        id: 'transfer',
        name: '文件传输',
        commands: [
            'bye',
            'ftp',
            'ftpcount',
            'ftpshut',
            'ftpwho',
            'ncftp',
            'tftp',
            'uucico',
            'uucp',
            'uupick',
            'uuto',
            'scp',
            'sftp',
            'rsync',
        ],
    },
    {
        id: 'archive',
        name: '备份压缩',
        commands: [
            'ar',
            'bunzip2',
            'bzip2',
            'bzip2recover',
            'compress',
            'cpio',
            'dump',
            'gunzip',
            'gzexe',
            'gzip',
            'lha',
            'restore',
            'tar',
            'unarj',
            'unzip',
            'zip',
            'zipinfo',
            '7z',
            'xz',
            'zcat',
        ],
    },
    {
        id: 'file',
        name: '文件管理',
        commands: [
            'diff',
            'diffstat',
            'file',
            'find',
            'git',
            'gitview',
            'ln',
            'locate',
            'lsattr',
            'mattrib',
            'mc',
            'mcopy',
            'mdel',
            'mdir',
            'mktemp',
            'mmove',
            'mread',
            'mren',
            'mshowfat',
            'mtools',
            'mtoolstest',
            'mv',
            'od',
            'paste',
            'patch',
            'rcp',
            'rhmask',
            'rm',
            'slocate',
            'split',
            'tee',
            'tmpwatch',
            'touch',
            'umask',
            'whereis',
            'which',
            'cat',
            'chattr',
            'chgrp',
            'chmod',
            'chown',
            'cksum',
            'cmp',
            'cp',
            'cut',
            'indent',
        ],
    },
    {
        id: 'disk',
        name: '磁盘管理',
        commands: [
            'cd',
            'df',
            'dirs',
            'du',
            'edquota',
            'eject',
            'lndir',
            'ls',
            'mcd',
            'mdeltree',
            'mdu',
            'mkdir',
            'mlabel',
            'mmd',
            'mmount',
            'mrd',
            'mzip',
            'pwd',
            'quota',
            'quotacheck',
            'quotaoff',
            'quotaon',
            'repquota',
            'rmdir',
            'rmt',
            'stat',
            'tree',
            'umount',
            'mount',
        ],
    },
    {
        id: 'disk-maint',
        name: '磁盘维护',
        commands: [
            'badblocks',
            'cfdisk',
            'dd',
            'e2fsck',
            'ext2ed',
            'fdisk',
            'fsck.ext2',
            'fsck',
            'fsck.minix',
            'fsconf',
            'hdparm',
            'losetup',
            'mbadblocks',
            'mformat',
            'mkbootdisk',
            'mkdosfs',
            'mke2fs',
            'mkfs.ext2',
            'mkfs',
            'mkfs.minix',
            'mkfs.msdos',
            'mkinitrd',
            'mkisofs',
            'mkswap',
            'mpartition',
            'sfdisk',
            'swapoff',
            'swapon',
            'symlinks',
            'sync',
        ],
    },
    {
        id: 'sys-config',
        name: '系统设置',
        commands: [
            'alias',
            'apmd',
            'aumix',
            'bind',
            'chkconfig',
            'chroot',
            'clock',
            'crontab',
            'declare',
            'depmod',
            'dircolors',
            'dmesg',
            'enable',
            'eval',
            'export',
            'fbset',
            'grpconv',
            'grpunconv',
            'hwclock',
            'insmod',
            'kbdconfig',
            'lilo',
            'liloconfig',
            'lsmod',
            'minfo',
            'mkkickstart',
            'modinfo',
            'modprobe',
            'mouseconfig',
            'ntsysv',
            'passwd',
            'pwconv',
            'pwunconv',
            'rdate',
            'resize',
            'rmmod',
            'rpm',
            'set',
            'setconsole',
            'setenv',
            'setup',
            'sndconfig',
            'timeconfig',
            'ulimit',
            'unalias',
            'unset',
            'systemctl',
            'journalctl',
        ],
    },
    {
        id: 'sys-admin',
        name: '系统管理',
        commands: [
            'adduser',
            'chfn',
            'chsh',
            'date',
            'exit',
            'finger',
            'free',
            'fwhois',
            'gitps',
            'groupdel',
            'groupmod',
            'halt',
            'id',
            'kill',
            'last',
            'lastb',
            'login',
            'logname',
            'logout',
            'logrotate',
            'newgrp',
            'nice',
            'procinfo',
            'ps',
            'pstree',
            'reboot',
            'renice',
            'rlogin',
            'rsh',
            'rwho',
            'screen',
            'shutdown',
            'sliplogin',
            'su',
            'sudo',
            'suspend',
            'swatch',
            'tload',
            'top',
            'uname',
            'useradd',
            'userconf',
            'userdel',
            'usermod',
            'vlock',
            'w',
            'who',
            'whoami',
            'whois',
            'htop',
            'killall',
        ],
    },
    {
        id: 'text',
        name: '文本处理',
        commands: [
            'awk',
            'col',
            'colrm',
            'comm',
            'csplit',
            'ed',
            'egrep',
            'ex',
            'fgrep',
            'fmt',
            'fold',
            'grep',
            'ispell',
            'jed',
            'joe',
            'join',
            'look',
            'mtype',
            'pico',
            'rgrep',
            'sed',
            'sort',
            'spell',
            'tr',
            'uniq',
            'vi',
            'wc',
            'nano',
            'less',
            'more',
            'head',
            'tail',
        ],
    },
    {
        id: 'network',
        name: '网络通讯',
        commands: [
            'dip',
            'getty',
            'mingetty',
            'ppp-off',
            'smbd',
            'telnet',
            'uulog',
            'uustat',
            'uux',
            'cu',
            'dnsconf',
            'efax',
            'httpd',
            'ip',
            'ifconfig',
            'mesg',
            'minicom',
            'nc',
            'netconf',
            'netconfig',
            'netstat',
            'ping',
            'ping6',
            'pppstats',
            'samba',
            'setserial',
            'shapecfg',
            'statserial',
            'talk',
            'tcpdump',
            'testparm',
            'traceroute',
            'tty',
            'uuname',
            'wall',
            'write',
            'ytalk',
            'arpwatch',
            'apachectl',
            'smbclient',
            'pppsetup',
            'ssh',
            'curl',
            'wget',
            'nmap',
            'nmtui',
            'l2ping',
            'firewalld',
            'iptables',
            'ss',
            'dig',
            'nslookup',
            'host',
        ],
    },
    {
        id: 'device',
        name: '设备管理',
        commands: ['dumpkeys', 'loadkeys', 'MAKEDEV', 'rdev', 'setleds', 'lsusb', 'lspci'],
    },
    {
        id: 'mail',
        name: '电子邮件与新闻组',
        commands: [
            'archive',
            'ctlinnd',
            'elm',
            'getlist',
            'inncheck',
            'mail',
            'mailconf',
            'mailq',
            'messages',
            'metamail',
            'mutt',
            'nntpget',
            'pine',
            'slrn',
            'reconfig',
            'startx',
            'Xconfigurator',
            'XF86Setup',
            'xlsatoms',
            'xlsclients',
            'xlsfonts',
        ],
    },
    {
        id: 'cloud',
        name: '容器与云原生',
        commands: [
            'docker',
            'kubectl',
            'helm',
            'ansible',
            'podman',
            'containerd',
            'crictl',
        ],
    },
    {
        id: 'other',
        name: '其他命令',
        commands: ['yes'],
    },
];

/**
 * @param {Array<{n:string,p:string,d:string}>} commands
 */
export function buildCategoryGroups(commands) {
    const byName = new Map(commands.map((item) => [item.n, item]));
    const assigned = new Set();
    const groups = CATEGORIES.map((category) => {
        const items = [];
        for (const name of category.commands) {
            const found = byName.get(name);
            if (found && !assigned.has(name)) {
                items.push(found);
                assigned.add(name);
            }
        }
        return {
            id: category.id,
            name: category.name,
            items,
            count: items.length,
        };
    }).filter((group) => group.count > 0);

    const uncategorized = commands.filter((item) => !assigned.has(item.n));
    if (uncategorized.length) {
        groups.push({
            id: 'uncategorized',
            name: '未分类',
            items: uncategorized,
            count: uncategorized.length,
        });
    }
    return groups;
}

/**
 * @param {Array<{n:string,p:string,d:string}>} commands
 * @returns {Map<string, Array<{n:string,p:string,d:string}>>}
 */
export function buildRelatedMap(commands, limit = 6) {
    const groups = buildCategoryGroups(commands);
    const map = new Map();
    for (const group of groups) {
        for (const cmd of group.items) {
            map.set(
                cmd.n,
                group.items.filter((item) => item.n !== cmd.n).slice(0, limit),
            );
        }
    }
    return map;
}

/**
 * @param {string} commandName
 * @param {Array<{n:string,p:string,d:string}>} commands
 * @param {number} limit
 */
export function relatedCommands(commandName, commands, limit = 6) {
    const map = buildRelatedMap(commands, limit);
    return map.get(commandName) || [];
}
